name: 'Docker & Terraform Deployment'
on:
  push:
    branches:
      - master

env:
  ROLE_TO_ASSUME: arn:aws:iam::726363461405:role/GithubOIDCDeployment

permissions:
  id-token: write
  contents: read

jobs:
  docker: 
    name: 'Upload Docker Image to ECR'
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: bash
    
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.ROLE_TO_ASSUME}}
          role-session-name: ecr-upload-role
          aws-region: ap-southeast-2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env: 
          REGISTRY: ${{ steps.login-ecr.outputs.REGISTRY }}
          REPOSITORY: ogc-cloudtechchallenge-private
          IMAGE_TAG: latest
        run: |
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG --build-arg="arch=amd64" .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

  terraform:
    name: 'Deploy Infrastructure'
    needs: docker
    runs-on: ubuntu-latest
    defaults: 
      run: 
        shell: bash
        working-directory: infra

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{env.ROLE_TO_ASSUME}}
          role-session-name: github-deployment
          aws-region: ap-southeast-2
    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialise Terraform
        run: terraform init

      - name: Terraform Format
        run: terraform fmt

      - name: Plan Terraform
        run: terraform plan -input=false

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
